version: '3'
services:
  auth_service:
    build: .
    container_name: auth_service
    ports:
      - "5003:5000"
    expose:
      - 5000
    networks:
      - mynetwork
networks:
  mynetwork:
    external: true
